version: "3.1"
services:
  mysql-db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: flask
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: 127.0.0.1
#      MYSQL_ROOT_HOST: 0.0.0.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  app:
    depends_on:
      - mysql-db
    build: ./app
    links:
      - mysql-db
    ports:
      - "8000:5000"


#version: '3.1'
#
#services:
#
#  db:
#    image: mysql:8.0
#    container_name: mysqlserver
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
